module.exports = {
	app:{
		code2Session:'/app/code2Session'
	},
	user:{
		register:'/user/register',
		login:'/user/login',
		myinfo:'/user/my-info',
	},
	file:{
		upload:'/file/upload'
	},
	shop:{
		add:'/shop/add',
		edit:'/shop/edit',
		audit:'/shop/audit',
		my:'/shop/query-my',
		queryaudit:'/shop/query-audit',
		detail:'/shop/detail',
	},
	activity:{
		query:'/activity/query',
		create:'/activity/create',
		join:'/activity/join',
		leave:'/activity/leave',
		edit:'/activity/edit',
		detail:'/activity/detail',
	}
}